github action #49

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -31,7 +31,7 @@ jobs:
       run: |
         apt update
         apt install -y ninja-build build-essential libgl1-mesa-dev libglu1-mesa-dev rsync \
-        qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools cmake wget
+        qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools cmake wget libfuse2
 
     - name: Download and Setup linuxdeployqt
       run: |
@@ -46,9 +46,15 @@ jobs:
 
     - name: Package AppImage
       run: |
-        linuxdeployqt build/Forex-Calculator -appimage
-        mkdir -p artifacts
-        mv Forex-Calculator*.AppImage artifacts/Forex-Calculator_linux.AppImage
+        if ! linuxdeployqt build/Forex-Calculator -appimage; then
+          echo "FUSE not found, extracting AppImage manually."
+          /usr/local/bin/linuxdeployqt --appimage-extract
+          mkdir -p artifacts
+          mv squashfs-root Forex-Calculator_linux.AppImage
+        else
+          mkdir -p artifacts
+          mv Forex-Calculator*.AppImage artifacts/Forex-Calculator_linux.AppImage
+        fi
 
     - name: Upload Artifact (Linux)
       uses: actions/upload-artifact@v4
