github action #86

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -22,7 +22,7 @@ jobs:
         sudo apt update
         sudo apt install -y ninja-build build-essential qt6-base-dev \
           libgl1-mesa-dev libglu1-mesa-dev rsync cmake patchelf qt6-tools-dev qt6-l10n-tools
-          
+
     - name: Configure CMake (Linux)
       run: |
         cmake -B build -DCMAKE_BUILD_TYPE=Release \
@@ -38,13 +38,11 @@ jobs:
         mkdir -p package
         cp build/Forex-Calculator package/
         linuxdeployqt package/Forex-Calculator -bundle-non-qt-libs
-      shell: bash
 
     - name: Package Linux Executable
       run: |
         mkdir artifacts
         tar -czvf artifacts/Forex-Calculator_Linux.tar.gz -C package .
-      shell: bash
 
     - name: Upload Artifact (Linux)
       uses: actions/upload-artifact@v4
@@ -68,18 +66,24 @@ jobs:
     - name: Build Forex-Calculator (macOS)
       run: cmake --build build --config Release
 
+    - name: Verify Executable
+      run: |
+        ls build/
+        if [ ! -f "build/Forex-Calculator" ]; then
+          echo "Executable not found!"
+          exit 1
+        fi
+
     - name: Deploy macOS App Bundle
       run: |
         mkdir -p package/Forex-Calculator.app/Contents/MacOS
         cp build/Forex-Calculator package/Forex-Calculator.app/Contents/MacOS/
-        macdeployqt package/Forex-Calculator.app -dmg
-      shell: bash
+        /usr/local/opt/qt/bin/macdeployqt package/Forex-Calculator.app -dmg
 
     - name: Package macOS Executable
       run: |
         mkdir -p artifacts
         zip -r artifacts/Forex-Calculator_macOS.zip package/Forex-Calculator.app
-      shell: bash
 
     - name: Upload Artifact (macOS)
       uses: actions/upload-artifact@v4
